### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by XakepSDK** [flagrow/sitemap#2]
I installed this and `forum.url/sitemap.xml` is not available due to 404 error.
I created post, then re-checked - still 404.

**Comment by clarkwinkelmann** [comment]
There's a discussion and a note in the first post at https://discuss.flarum.org/d/14941-flagrow-sitemap that's probably related.

Let me know if it fixes it or if you're facing a different issue.

Copied for reference:

If you are running nginx, it's possible that `/sitemap.xml` will return the 404 error of nginx instead of being handled by Flarum. In this case you can try adding the following line to your site config, below the `location / {}` block of Flarum or at the end of the config. See posts below where we discussed this fix for more details.

    location = /sitemap.xml { try_files $uri $uri/ /index.php?$query_string; }

**Comment by XakepSDK** [comment]
Yep, it works! Thank you very much.
